### ISSUE TITLE
Exclude unknown users from Leaderboard

### ISSUE THREAD

**Issue by dbnoble** [drako-gaming/website#30]
Currently, there are many users on the leaderboard who are named “user”. I’m assuming these are users who have been created by being in chat but have never actually authenticated through the website and haven’t been assigned their display name.

I feel it would be a better user experience if these users were excluded from the leaderboard rankings until they have actually signed in since it offers no prestige when they are unnamed.

A simple conditional when the list is constructed can exclude them before ranking.

**Comment by SirRippovMaple** [comment]
This is not a current bug, but rather just a result of an earlier problem with the database. There won't be any unknown users if we start from a fresh database.

**Comment by SirRippovMaple** [comment]
To clarify, you won't be able to earn any scales without being "known". If you earn scales from the site, you must be logged in, and that way your user name is known. If you earn scales as a result of redeeming a reward, your username is provided by the webhook payload (this case was not catered for in the past, hence unknown users in our test database).
